name: Mirror to Codeberg (disabled)
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  mirror:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/yorukot/superfile.git'
          GIT_USERNAME: yorukot
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
          PUSH_ALL_REFS: "true"
